#!/bin/sh

ins_pid=$(pidof insurgency_linux)
#ins_pid=$(pidof firefox)
if [ -z "$ins_pid" ]; then
    /bin/echo -e "\e[31mCannot find Insurgency process.\e[0m"
    exit 1
fi

#Credit: Aixxe @ aixxe.net
if grep -q libAimTux.so /proc/$ins_pid/maps; then
    /bin/echo -e "\e[33mAlready injected.\e[0m"
    exit
fi

/bin/echo -e "Insurgency PID: \e[31m$ins_pid\e[0m\n"

sudo gdb -n -q -batch \
  -ex "attach $ins_pid" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "set \$dlerror = (char*(*)(void)) dlerror" \
  -ex "call \$dlopen(\"$(pwd)/libInsTux.so\", 1)" \
  -ex "call \$dlerror()" \
  -ex "detach" \
  -ex "quit"
