#!/bin/sh

if grep -q libInsTux.so /proc/$(pidof insurgency_linux)/maps; then
sudo gdb -n -q -batch \
    -ex "attach $(pidof insurgency_linux)" \
    -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
    -ex "set \$dlclose = (int(*)(void*)) dlclose" \
    -ex "set \$library = \$dlopen(\"$(pwd)/libInsTux.so\", 6)" \
    -ex "call \$dlclose(\$library)" \
    -ex "call \$dlclose(\$library)" \
    -ex "detach" \
    -ex "quit"
fi
